### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by AlexisMoDz** [MoosheTV/PropHuntV#1]
Hello, first of all, thank you for this gamemode!
Good I'm French so my english is really bad, sorry ^^

I would like to know what happens if we ban a player? Is there a system for administrators?
If so, could you tell me more?

**Comment by MoosheTV** [comment]
No, this is a standalone prophunt resource. Any administrative tools needed would need to be handled by a different resource.

You can go into `data/players/[SteamID].json` to get identifiers (ip, gta license hash, etc.) to cross-reference with your administrative tool.

If you come across anyone cheating mechanics specific to this resource, let me know, and I'll try to patch it ASAP.
