### ISSUE TITLE
Error System.Runtime.InteropServices.RuntimeInformation.net

### ISSUE THREAD

**Issue by ghost** [MoosheTV/PropHuntV#12]
How can I add a System.Runtime.InteropServices.RuntimeInformation.net on Visual Studio ? Plugin don't work, I want to translate this script but can not compile it

**Comment by Tindergarten** [comment]
I had the same problem previously. Change the System.Runtime.InteropServices.RuntimeInformation from nuget to System.Runtime.InteropServices.RuntimeInformation.net and it'll work.

**Comment by ghost** [comment]
Thanks
